import { StyleSheet } from 'react-native';
import { Colors } from './Colors';

export default (colorScheme: 'light' | 'dark') => {
    const themeColors = Colors[colorScheme ?? 'light'];
    return StyleSheet.create({
        error: {
            color: 'red',
            marginTop: 10,
        },
        frontContainer: {
            flex: 1,
            padding: 16,
            height: '100%',
            width: '100%',
        },
        frontSideOfCard: {
            flex: 1,
            marginTop: 30,
            padding: 20,
            borderWidth: 0.5,
            borderRadius: 20,
            backgroundColor: themeColors.cardBackground,
            height: '100%',
        },
        numberText: {
            position: 'absolute',
            fontFamily: 'ZainBold',
            top: -12,
            left: -12,
            width: 80,
            height: 80,
            borderRadius: 40,
            borderWidth: 1,
            textAlign: 'center',
            textAlignVertical: 'center',
            fontSize: 36,
            fontWeight: 'bold',
            color: themeColors.nummerCircleText,
            backgroundColor: Colors[colorScheme].nummerCircleBackground,
        },
        ausgangsgedanke: {
            fontFamily: 'ZainItalic',
            fontSize: 20,
            textAlign: 'center',
            lineHeight: 22,
            paddingTop: 0,
            paddingLeft: 70,
            width: '100%',
            color: themeColors.ausgangsgedanke,
        },
        ausgangsgedankeInWA: {
            fontFamily: 'ZainItalic',
            paddingTop: 30,
            fontSize: 22,
            lineHeight: 24,
            textAlign: 'center',
            color: themeColors.ausgangsgedankeInWA,
        },
        gedankeContainer: {
            height: '50%',
        },
        gedanke: {
            height: '100%',
            fontSize: 22,
            fontFamily: 'OverlockRegular',
            alignItems: 'center',
            textAlign: 'left',
            color: themeColors.gedanke,
        },
        gedankeKurz: {
            fontFamily: 'OverlockRegular',
            fontSize: 24,
            lineHeight: 32,
            textAlign: 'center',
            marginVertical: 20,
            color: themeColors.gedanke,
        },
        eyes: {
            fontSize: 36,
        },
        comment: {
            position: 'absolute',
            bottom: 10,
            left: 0,
            right: 0,
            fontSize: 28,
            textAlign: 'center',
            alignSelf: 'center',
            width: '100%',
            letterSpacing: 6,
        },
        commentChoices: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 20,
        },
        commentChoiceOk: {
            fontSize: 40,
        },
        commentChoiceVoter: {
            width: 64,
            height: 64,
        },
        weltanschauung: {
            fontFamily: 'ZainBold',
            fontSize: 36,
            textAlign: 'left',
            marginTop: 10,
        },
        autorName: {
            fontFamily: 'ZainRegular',
            fontSize: 22,
            textAlign: 'left',
            marginTop: -5,
        },
        model: {
            fontSize: 10,
            textAlign: 'center',
            marginTop: 4,
            marginBottom: 5,
        },
        bottomTexts: {
            position: 'absolute',
            bottom: 0,
            left: 30,
            flexDirection: 'column',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        autorOverlayContainer: {
            position: 'absolute',
            width: '100%',
            bottom: 16,
            left: 16,
        },
        imageEllipse: {
            position: 'absolute',
            right: 20,
            bottom: 60,
            width: 80,
            height: 60,
            justifyContent: 'center',
            alignItems: 'center',
        },
        autorImage: {
            width: 170,
            height: 220,
            borderRadius: 25,
        },
        backSideOfCard: {
            flex: 1,
            marginTop: 30,
            padding: 20,
            borderWidth: 0.5,
            borderRadius: 20,
            backgroundColor: themeColors.cardBackground,
            height: '100%',
        },
        backHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            width: '100%',
            paddingRight: 10,
        },
        backAusgangsgedanke: {
            fontFamily: 'ZainItalic',
            fontSize: 24,
            lineHeight: 32,
            flex: 1,
            paddingRight: 20,
            color: themeColors.ausgangsgedanke,
        },
        backNumberText: {
            fontFamily: 'ZainBold',
            width: 80,
            height: 80,
            borderRadius: 40,
            borderWidth: 1,
            textAlign: 'center',
            textAlignVertical: 'center',
            fontSize: 36,
            fontWeight: 'bold',
            color: themeColors.nummerCircleText,
            backgroundColor: Colors[colorScheme].nummerCircleBackground,
        },
    });
};
